# Generated by Django 5.0.4 on 2026-09-04 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='product.category', verbose_name='دسته اصلی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی کالا',
                'verbose_name_plural': 'دسته\u200cبندی کالاها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='کد دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='product.categoryform', verbose_name='دسته اصلی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی کالا',
                'verbose_name_plural': 'دسته\u200cبندی کالاها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='کد کالا / SKU')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='عکس')),
                ('unit', models.CharField(choices=[('number', 'عدد'), ('package', 'بسته'), ('carton', 'کارتن'), ('kg', 'کیلوگرام'), ('liter', 'لیتر'), ('meter', 'متر')], default='number', max_length=20, verbose_name='واحد')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت خرید')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت عمده')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش')),
                ('current_stock', models.IntegerField(default=0, verbose_name='موجودی فعلی')),
                ('min_stock', models.IntegerField(default=0, verbose_name='حداقل موجودی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('out_of_stock', 'ناموجود')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین خرید')),
                ('last_sale_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین فروش')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['-created_at'],
            },
        ),
    ]
