# Generated by Django 5.0.4 on 2026-09-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryForm',
        ),
    ]
