# Generated by Django 5.0.4 on 2026-09-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_categoryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_stock',
            field=models.IntegerField(default=0, verbose_name='موجودی دوکان'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_stock',
            field=models.IntegerField(default=0, verbose_name='موجودی گدام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='موجودی کل'),
        ),
    ]
