# Generated by Django 5.0.4 on 2026-09-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_shop_stock_product_stock_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
