# Generated by Django 5.0.4 on 2026-09-05 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_delete_categoryform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'ورود کالا'), ('OUT', 'خروج کالا'), ('ADJUSTMENT', 'تعدیل موجودی'), ('RETURN', 'برگشت کالا'), ('DAMAGE', 'کالای آسیب\u200cدیده'), ('TRANSFER', 'انتقال کالا')], max_length=20, verbose_name='نوع حرکت')),
                ('quantity', models.IntegerField(help_text='مثبت برای ورود، منفی برای خروج', verbose_name='تعداد')),
                ('stock_after_movement', models.IntegerField(blank=True, null=True, verbose_name='موجودی بعد از حرکت')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره مرجع (فاکتور/سفارش)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'حرکت کالا',
                'verbose_name_plural': 'حرکات کالا',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='stock_stock_product_467980_idx'), models.Index(fields=['movement_type'], name='stock_stock_movemen_b002ed_idx')],
            },
        ),
    ]
