# Generated by Django 5.0.4 on 2026-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_number',
            field=models.CharField(blank=True, default=1, max_length=100, unique=True, verbose_name='شماره مرجع'),
            preserve_default=False,
        ),
    ]
