# Generated by Django 5.0.4 on 2026-09-06 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_shop_stock_product_stock_stock_and_more'),
        ('stock', '0002_alter_stockmovement_reference_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.CharField(choices=[('shop', 'دوکان'), ('stock', 'گدام')], default=1, max_length=10, verbose_name='محل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'ورود کالا'), ('OUT', 'خروج کالا')], max_length=20, verbose_name='نوع حرکت'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['location'], name='stock_stock_locatio_8a5fcb_idx'),
        ),
    ]
