# Generated by Django 5.0.4 on 2026-09-12 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_parent'),
        ('stock', '0003_stockmovement_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='موجودی')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'موجودی',
                'verbose_name_plural': 'موجودی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد')),
                ('type', models.CharField(choices=[('shop', 'دوکان'), ('warehouse', 'گدام')], max_length=20, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'موقعیت',
                'verbose_name_plural': 'موقعیت\u200cها',
                'ordering': ['type', 'code'],
            },
        ),
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='stock_stock_locatio_8a5fcb_idx',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='product.product', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='stock.location', verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='stock.location', verbose_name='موقعیت'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['location', 'created_at'], name='stock_stock_locatio_ba7e72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'location')},
        ),
    ]
