"""
Django settings for poyafar_business project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ═══════════════════════════════════════════════════════════
# SECURITY
# ═══════════════════════════════════════════════════════════

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-19c8v4*dkra_hav(6=97&18$bij(va7r!#9v)4@cijptfoqu+q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# ═══════════════════════════════════════════════════════════
# APPLICATIONS
# ═══════════════════════════════════════════════════════════

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.product',
    'apps.stock',
    'apps.purchasesale',
    'apps.debts',
    'apps.treasury',
    'apps.expense',
    'apps.employee',
    'apps.reports',
    'apps.backup',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.backup.middleware.AutoBackupFallbackMiddleware',
]

ROOT_URLCONF = 'poyafar_business.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'poyafar_business' / 'templates',
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'poyafar_business.wsgi.application'


# ═══════════════════════════════════════════════════════════
# USER DATA DIRECTORY (writable location for DB and media)
# ═══════════════════════════════════════════════════════════
#
# When the app is packaged with PyInstaller, the bundled folders
# are read-only. So the database and uploaded media must live in
# the user's AppData folder — a writable, persistent location.
#
# On Windows this resolves to:
#   C:\Users\<username>\AppData\Roaming\PoyafarApp\
# ═══════════════════════════════════════════════════════════

USER_DATA_DIR = os.path.join(
    os.environ.get('APPDATA', os.path.expanduser('~')),
    'PoyafarApp'
)
os.makedirs(USER_DATA_DIR, exist_ok=True)


# ═══════════════════════════════════════════════════════════
# DATABASE — SQLite (in AppData)
# ═══════════════════════════════════════════════════════════

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(USER_DATA_DIR, 'db.sqlite3'),
    }
}


# ═══════════════════════════════════════════════════════════
# PASSWORD VALIDATION
# ═══════════════════════════════════════════════════════════

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ═══════════════════════════════════════════════════════════
# INTERNATIONALIZATION
# ═══════════════════════════════════════════════════════════

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kabul'
USE_I18N = True
USE_TZ = True


# ═══════════════════════════════════════════════════════════
# STATIC FILES (bundled with the app — read-only at runtime)
# ═══════════════════════════════════════════════════════════

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


# ═══════════════════════════════════════════════════════════
# MEDIA FILES (user uploads — must be writable, so AppData)
# ═══════════════════════════════════════════════════════════

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(USER_DATA_DIR, 'media')
os.makedirs(MEDIA_ROOT, exist_ok=True)


# ═══════════════════════════════════════════════════════════
# DEFAULT PRIMARY KEY
# ═══════════════════════════════════════════════════════════

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'