# Generated by Django 5.0.4 on 2026-09-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBackupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('hour', models.IntegerField(default=10, verbose_name='ساعت')),
                ('minute', models.IntegerField(default=0, verbose_name='دقیقه')),
                ('include_media', models.BooleanField(default=True, verbose_name='شامل مدیا')),
                ('keep_days', models.IntegerField(default=30, verbose_name='نگهداری (روز)')),
                ('keep_count', models.IntegerField(default=20, verbose_name='حداقل تعداد نگهداری')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اجرا')),
            ],
            options={
                'verbose_name': 'تنظیمات بکاپ خودکار',
                'verbose_name_plural': 'تنظیمات بکاپ خودکار',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسیر فایل')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('backup_type', models.CharField(choices=[('db', 'فقط دیتابیس'), ('full', 'کامل (دیتابیس + مدیا)')], default='full', max_length=20, verbose_name='نوع بکاپ')),
                ('trigger', models.CharField(choices=[('manual', 'دستی'), ('auto', 'خودکار')], default='manual', max_length=20, verbose_name='نحوه ساخت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
            ],
            options={
                'verbose_name': 'بکاپ',
                'verbose_name_plural': 'بکاپ\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
