# Generated by Django 5.0.4 on 2026-09-06 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_shop_stock_product_stock_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='شماره خرید')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ خرید')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='نام تأمین\u200cکننده')),
                ('quantity', models.IntegerField(verbose_name='تعداد کل')),
                ('to_shop', models.IntegerField(default=0, verbose_name='به دوکان')),
                ('to_stock', models.IntegerField(default=0, verbose_name='به گدام')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت خرید فی واحد')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مجموع خرید')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ پرداخت\u200cشده')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='باقی\u200cمانده')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
                'ordering': ['-created_at'],
            },
        ),
    ]
