# Generated by Django 5.0.4 on 2026-09-06 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_shop_stock_product_stock_stock_and_more'),
        ('purchasesale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='شماره فروش')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ فروش')),
                ('customer_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('location', models.CharField(choices=[('shop', 'دوکان'), ('stock', 'گدام')], default='shop', max_length=10, verbose_name='از محل')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت فروش فی واحد')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مجموع فروش')),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ دریافت\u200cشده')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='باقی\u200cمانده')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'فروش',
                'verbose_name_plural': 'فروش\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='purchasesal_product_9cda91_idx'), models.Index(fields=['location'], name='purchasesal_locatio_ebb983_idx')],
            },
        ),
    ]
