# Generated by Django 5.0.4 on 2026-09-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0002_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date', '-created_at'], 'verbose_name': 'خرید', 'verbose_name_plural': 'خریدها'},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='to_shop',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='to_stock',
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.JSONField(default=list, verbose_name='اقلام خرید'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='باقی\u200cمانده'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع خرید'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier_name'], name='purchasesal_supplie_b3a52a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_date'], name='purchasesal_purchas_7556df_idx'),
        ),
    ]
