# Generated by Django 5.0.4 on 2026-09-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0003_alter_purchase_options_remove_purchase_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date', '-created_at'], 'verbose_name': 'فروش', 'verbose_name_plural': 'فروش\u200cها'},
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='purchasesal_product_9cda91_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='purchasesal_locatio_ebb983_idx',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='items',
            field=models.JSONField(default=list, verbose_name='اقلام فروش'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='باقی\u200cمانده'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع فروش'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer_name'], name='purchasesal_custome_e49fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='purchasesal_sale_da_55aef5_idx'),
        ),
    ]
