# Generated by Django 5.0.4 on 2026-09-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0004_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='initial_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='پرداخت اولیه هنگام خرید'),
        ),
        migrations.AddField(
            model_name='sale',
            name='initial_received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='دریافت اولیه هنگام فروش'),
        ),
    ]
