# Generated by Django 5.0.4 on 2026-09-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0005_purchase_initial_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره خریدار'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره مشتری'),
        ),
    ]
