# Generated by Django 5.0.4 on 2026-09-13 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0006_purchase_supplier_number_sale_customer_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='شماره مرجوعی')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ مرجوعی')),
                ('customer_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('customer_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره مشتری')),
                ('items', models.JSONField(default=list, verbose_name='اقلام مرجوعی')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع مرجوعی')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ بازپرداخت\u200cشده')),
                ('remaining_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بستانکاری باقی\u200cمانده')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده')], default='confirmed', max_length=20, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_returns', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('original_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_returns', to='purchasesale.sale', verbose_name='فروش اصلی')),
            ],
            options={
                'verbose_name': 'مرجوعی از مشتری',
                'verbose_name_plural': 'مرجوعی\u200cهای مشتریان',
                'ordering': ['-return_date', '-created_at'],
                'indexes': [models.Index(fields=['customer_name'], name='purchasesal_custome_adca7b_idx'), models.Index(fields=['return_date'], name='purchasesal_return__7b0ed1_idx'), models.Index(fields=['status'], name='purchasesal_status_e2c8b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='شماره مرجوعی')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ مرجوعی')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='نام تأمین\u200cکننده')),
                ('supplier_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره تأمین\u200cکننده')),
                ('items', models.JSONField(default=list, verbose_name='اقلام مرجوعی')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع مرجوعی')),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ دریافت\u200cشده')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='باقی\u200cمانده')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده')], default='confirmed', max_length=20, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_returns', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('original_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_returns', to='purchasesale.purchase', verbose_name='خرید اصلی')),
            ],
            options={
                'verbose_name': 'مرجوعی به تأمین\u200cکننده',
                'verbose_name_plural': 'مرجوعی\u200cهای به تأمین\u200cکنندگان',
                'ordering': ['-return_date', '-created_at'],
                'indexes': [models.Index(fields=['supplier_name'], name='purchasesal_supplie_ac6516_idx'), models.Index(fields=['return_date'], name='purchasesal_return__9f84a3_idx'), models.Index(fields=['status'], name='purchasesal_status_42ad37_idx')],
            },
        ),
    ]
