# Generated by Django 5.0.4 on 2026-09-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0007_customerreturn_supplierreturn'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerreturn',
            name='purchasesal_status_e2c8b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierreturn',
            name='purchasesal_status_42ad37_idx',
        ),
        migrations.RemoveField(
            model_name='customerreturn',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerreturn',
            name='customer_number',
        ),
        migrations.RemoveField(
            model_name='customerreturn',
            name='original_sale',
        ),
        migrations.RemoveField(
            model_name='customerreturn',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='customerreturn',
            name='remaining_credit',
        ),
        migrations.RemoveField(
            model_name='customerreturn',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customerreturn',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='supplierreturn',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplierreturn',
            name='original_purchase',
        ),
        migrations.RemoveField(
            model_name='supplierreturn',
            name='received_amount',
        ),
        migrations.RemoveField(
            model_name='supplierreturn',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='supplierreturn',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supplierreturn',
            name='supplier_number',
        ),
        migrations.RemoveField(
            model_name='supplierreturn',
            name='total_amount',
        ),
    ]
