# Generated by Django 5.0.4 on 2026-09-13 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0008_remove_customerreturn_purchasesal_status_e2c8b1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='شماره ضایعات')),
                ('waste_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ضایعات')),
                ('reason', models.CharField(help_text='مثال: خرابی، تاریخ گذشته، شکستگی', max_length=200, verbose_name='دلیل ضایعات')),
                ('items', models.JSONField(default=list, verbose_name='اقلام ضایعات')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'ضایعات کالا',
                'verbose_name_plural': 'ضایعات کالاها',
                'ordering': ['-waste_date', '-created_at'],
                'indexes': [models.Index(fields=['reason'], name='purchasesal_reason_23c90f_idx'), models.Index(fields=['waste_date'], name='purchasesal_waste_d_773f07_idx')],
            },
        ),
    ]
