# Generated by Django 5.0.4 on 2026-09-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0009_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='هر ۱ دالر = چند افغانی', max_digits=15, verbose_name='نرخ دالر امروز'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_dollar_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع دالری'),
        ),
        migrations.AddField(
            model_name='sale',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='هر ۱ دالر = چند افغانی', max_digits=15, verbose_name='نرخ دالر امروز'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_dollar_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع دالری'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='initial_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='پرداخت اولیه'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع خرید (افغانی)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='initial_received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='دریافت اولیه'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع فروش (افغانی)'),
        ),
    ]
