# Generated by Django 6.0.4 on 2026-09-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0010_purchase_dollar_rate_purchase_total_dollar_amount_and_more'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerreturn',
            name='purchasesal_custome_adca7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerreturn',
            name='purchasesal_return__7b0ed1_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierreturn',
            name='purchasesal_supplie_ac6516_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierreturn',
            name='purchasesal_return__9f84a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='waste',
            name='purchasesal_reason_23c90f_idx',
        ),
        migrations.RemoveIndex(
            model_name='waste',
            name='purchasesal_waste_d_773f07_idx',
        ),
        migrations.AddField(
            model_name='customerreturn',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ بازپرداخت به مشتری'),
        ),
        migrations.AddField(
            model_name='customerreturn',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_return_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
        migrations.AddField(
            model_name='sale',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ دریافتی از تأمین\u200cکننده'),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_return_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='reason',
            field=models.CharField(max_length=200, verbose_name='دلیل ضایعات'),
        ),
    ]
