# Generated by Django 5.0.4 on 2026-09-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0011_remove_customerreturn_purchasesal_custome_adca7b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='هر ۱ دالر = چند افغانی', max_digits=15, null=True, verbose_name='نرخ دالر امروز'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='هر ۱ دالر = چند افغانی', max_digits=15, null=True, verbose_name='نرخ دالر امروز'),
        ),
    ]
