# Generated by Django 5.0.4 on 2026-09-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0012_alter_purchase_dollar_rate_alter_sale_dollar_rate'),
        ('treasury', '0003_transaction_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreturn',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_return_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='dollar_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='هر ۱ دالر = چند افغانی', max_digits=15, null=True, verbose_name='نرخ دالر امروز'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dollar_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='هر ۱ دالر = چند افغانی', max_digits=15, null=True, verbose_name='نرخ دالر امروز'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
        migrations.AlterField(
            model_name='supplierreturn',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
    ]
