# Generated by Django 5.0.4 on 2026-09-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasesale', '0013_alter_customerreturn_treasury_transaction_and_more'),
        ('treasury', '0003_transaction_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreturn',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_returns', to='purchasesale.sale', verbose_name='فروش اصلی'),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='original_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='purchasesale.purchase', verbose_name='خرید اصلی'),
        ),
        migrations.AddIndex(
            model_name='customerreturn',
            index=models.Index(fields=['original_sale', 'return_date'], name='purchasesal_origina_4449f3_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierreturn',
            index=models.Index(fields=['original_purchase', 'return_date'], name='purchasesal_origina_79106e_idx'),
        ),
    ]
