# Generated by Django 5.0.4 on 2026-09-07 09:10

import django.utils.timezone
import imagekit.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_afg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='موجودی افغانی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'خزانه',
                'verbose_name_plural': 'خزانه',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره تراکنش')),
                ('transaction_type', models.CharField(choices=[('IN', 'واریز'), ('OUT', 'برداشت')], max_length=3, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مقدار')),
                ('from_who', models.CharField(max_length=200, verbose_name='از چه کسی')),
                ('money_type', models.CharField(choices=[('SARAFI', 'صرافی'), ('BANK', 'بانک'), ('PERSONAL', 'شخصی'), ('LOAN', 'قرض'), ('PURCHASE', 'خرید'), ('SALE', 'فروش'), ('PURCHASE_DEBT', 'پرداخت بدهی خرید'), ('SALE_DEBT', 'دریافت بدهی فروش')], max_length=20, verbose_name='نوع پول')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('transaction_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='transaction_image/', verbose_name='تصویر تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='treasury_tr_date_c878fb_idx'), models.Index(fields=['transaction_type'], name='treasury_tr_transac_baed4e_idx'), models.Index(fields=['money_type'], name='treasury_tr_money_t_68d69e_idx')],
            },
        ),
    ]
