# Generated by Django 5.0.4 on 2026-09-14 09:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('AFG', 'افغانی'), ('USD', 'دالر')], default='AFG', max_length=5, verbose_name='ارز'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='balance_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='موجودی دالر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='money_type',
            field=models.CharField(choices=[('SARAFI', 'صرافی'), ('BANK', 'بانک'), ('PERSONAL', 'شخصی'), ('LOAN', 'قرض'), ('PURCHASE', 'خرید'), ('SALE', 'فروش'), ('PURCHASE_DEBT', 'پرداخت بدهی خرید'), ('SALE_DEBT', 'دریافت بدهی فروش'), ('CUSTOMER_RETURN', 'مرجوعی مشتری'), ('SUPPLIER_RETURN', 'مرجوعی به تأمین\u200cکننده'), ('EXPENSE', 'مصرف'), ('SALARY', 'معاش'), ('OTHER', 'سایر')], max_length=20, verbose_name='نوع پول'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['currency'], name='treasury_tr_currenc_875570_idx'),
        ),
    ]
