# Generated by Django 5.0.4 on 2026-09-11 14:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
                ('father_name', models.CharField(max_length=200, verbose_name='نام پدر')),
                ('tazkera_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تذکره')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='عکس کارمند')),
                ('tazkera_image', models.ImageField(blank=True, null=True, upload_to='employees/tazkera/', verbose_name='عکس تذکره')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='وظیفه / سمت')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شمولیت')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='تاریخ منفکی')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='معاش پایه (افغانی)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['full_name'], name='employee_em_full_na_fe246b_idx'), models.Index(fields=['phone_number'], name='employee_em_phone_n_ca8436_idx'), models.Index(fields=['join_date'], name='employee_em_join_da_bb5adf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.CharField(max_length=20, verbose_name='ماه معاش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار معاش (افغانی)')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employee.employee', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'معاش',
                'verbose_name_plural': 'معاشات',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'payment_date'], name='employee_sa_employe_6e1a69_idx'), models.Index(fields=['salary_month'], name='employee_sa_salary__da98ca_idx')],
            },
        ),
    ]
