# Generated by Django 5.0.4 on 2026-09-07 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasesale', '0004_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ پرداختی')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='purchasesale.purchase', verbose_name='خرید')),
            ],
            options={
                'verbose_name': 'پرداخت بدهی خرید',
                'verbose_name_plural': 'پرداخت\u200cهای بدهی خرید',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['purchase', 'payment_date'], name='debts_purch_purchas_5e9bfa_idx')],
            },
        ),
    ]
