# Generated by Django 5.0.4 on 2026-09-07 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        ('purchasesale', '0004_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ دریافتی')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ دریافت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='purchasesale.sale', verbose_name='فروش')),
            ],
            options={
                'verbose_name': 'دریافت بدهی فروش',
                'verbose_name_plural': 'دریافت\u200cهای بدهی فروش',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['sale', 'payment_date'], name='debts_saled_sale_id_02f0a4_idx')],
            },
        ),
    ]
