# Generated by Django 6.0.4 on 2026-09-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_saledebt'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebt',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_debt_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
        migrations.AddField(
            model_name='saledebt',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_debt_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
    ]
