# Generated by Django 5.0.4 on 2026-09-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_purchasedebt_treasury_transaction_and_more'),
        ('purchasesale', '0013_alter_customerreturn_treasury_transaction_and_more'),
        ('treasury', '0003_transaction_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedebt',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='purchasesale.purchase', verbose_name='خرید'),
        ),
        migrations.AlterField(
            model_name='purchasedebt',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_debt_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
        migrations.AlterField(
            model_name='saledebt',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='purchasesale.sale', verbose_name='فروش'),
        ),
        migrations.AlterField(
            model_name='saledebt',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_debt_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
    ]
