# Generated by Django 5.0.4 on 2026-09-15 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_alter_purchasedebt_purchase_and_more'),
        ('purchasesale', '0013_alter_customerreturn_treasury_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedebt',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='purchasesale.purchase', verbose_name='خرید'),
        ),
        migrations.AlterField(
            model_name='saledebt',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='purchasesale.sale', verbose_name='فروش'),
        ),
    ]
