# Generated by Django 5.0.4 on 2026-09-11 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='شماره مصرف')),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ مصرف')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مصرف')),
                ('items', models.JSONField(default=list, verbose_name='اقلام مصرف')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع کل (افغانی)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='expenses/', verbose_name='عکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'مصرف',
                'verbose_name_plural': 'مصارف',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='expense_exp_expense_46ea33_idx'), models.Index(fields=['expense_number'], name='expense_exp_expense_07cc50_idx')],
            },
        ),
    ]
