# Generated by Django 5.0.4 on 2026-09-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_treasury_transaction'),
        ('treasury', '0003_transaction_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='treasury_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions', to='treasury.transaction', verbose_name='تراکنش'),
        ),
    ]
